version: '3.8'
services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: cib
    container_name: cib
    volumes:
      - ./users.csv:/app/users.csv
      - ./settings.py:/app/settings.py
    restart: always
